//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLSP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.InvoiceIns = new HashSet<InvoiceIn>();
            this.InvoiceOuts = new HashSet<InvoiceOut>();
            this.Accounts = new HashSet<Account>();
        }

        [Required(ErrorMessage = "Vui lòng thông tin cho trường này")]
        public int Emp_ID { get; set; }
        [Required(ErrorMessage = "Vui lòng thông tin cho trường này")]
        public string Emp_Name { get; set; }
        [Required(ErrorMessage = "Vui lòng thông tin cho trường này")]
        public string Emp_Phone { get; set; }
      
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceIn> InvoiceIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceOut> InvoiceOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
