//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLSP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.InvoiceIns = new HashSet<InvoiceIn>();
        }
        [Required(ErrorMessage = "Vui lòng thông tin cho trường này")]
        public string Sup_ID { get; set; }
        [Required(ErrorMessage = "Vui lòng thông tin cho trường này")]
        public string Sup_Name { get; set; }
        [Required(ErrorMessage = "Vui lòng thông tin cho trường này")]
        public string Sup_Address { get; set; }
        [Required(ErrorMessage = "Vui lòng thông tin cho trường này")]
        public string Sup_Phone { get; set; }
        public bool isDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceIn> InvoiceIns { get; set; }
    }
}
